name: "Android Build QA"
on:
    workflow_dispatch:
        # inputs:
        #     UPLOAD_ARTIFACTS_TO_GITHUB:
        #       description: 'Whether or not to upload to GitHub for manual download'
        #       required: false
        #       default: true
        #       type: boolean
jobs:
  build:
    runs-on: ubuntu-latest
    environment: qa
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: "17.x"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.5"
          channel: 'stable'
      - run: flutter pub get
      - name: Run Tests
        run: flutter test
      - name: Build apk 
        run: |
              echo "Building apk"
              flutter build apk -t lib/main.dart 
      - name: Move build and rename for upload
        run: |
            mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/ANDROID-build.apk
            ls -al build/app/outputs/flutter-apk

      - name: Upload Artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: QuickQuest 
          path: |
            build/app/outputs/flutter-apk/ANDROID-build.apk